services:
  - type: web
    name: voluntarios-backend
    runtime: node
    buildCommand: cd backend && npm ci --only=production
    startCommand: cd backend && npm start
    plan: free
    rootDir: backend
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000